services:
  
  client: 
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_APP_BACKEND_ADDRESS=https://localhost/api/prod
    container_name: crash-test-client-prod
    restart: always
    networks:
      - network
    # depends_on:
    #   - traefik

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: crash-test-server
    ports:
      - "3001:3001"
    # labels:
    #   - "traefik.http.routers.server.rule=(Host(`client.localhost`) && PathPrefix(`/api`))"
    restart: always
    # depends_on:
    #   - traefik

  # traefik: 
  #   image: traefik:v2.11
  #   command: --api.insecure=true --providers.docker
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

networks:
  network: 
