services:
  client: 
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        - VITE_APP_BACKEND_ADDRESS=https://localhost/api/prod
    container_name: crash-test-client-prod
    restart: always
    networks:
      - network

networks:
  network: